### ISSUE TITLE
Getting an ArgumentNullException

### ISSUE THREAD

**Issue by daveblack101** [EtchUK/Etch.OrchardCore.Blocks#75]
The following is what's logged:

`2023-06-07 02:58:30.3982|Default|00-22f6c8e3c4a46a3fd2974c611ba0dd06-eb689c26c8c271dc-00||OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator
|ERROR|List`1 thrown from BuildDisplayAsync by ArgumentNullException System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Etch.OrchardCore.Blocks.EditorJS.Parsers.BlocksParser.RenderAsync(BlockParserContext context, String data) in 
   C:\Users\black\Apps\DevOps\Reducted\src\Modules\Etch.OrchardCore.Blocks\EditorJS\Parsers\BlocksParser.cs:line 106
   at Etch.OrchardCore.Blocks.EditorJS.Parsers.BlocksParser.RenderAsync(BlockBodyPart part) in 
   C:\Users\black\Apps\DevOps\Reducted\src\Modules\Etch.OrchardCore.Blocks\EditorJS\Parsers\BlocksParser.cs:line 76
   at Etch.OrchardCore.Blocks.Drivers.BlockBodyPartDisplay.DisplayAsync(BlockBodyPart part, BuildPartDisplayContext context) in 
   C:\Users\black\Apps\DevOps\Reducted\src\Modules\Etch.OrchardCore.Blocks\Drivers\BlockBodyPartDisplay.cs:line 31
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`
   1.OrchardCore.ContentManagement.Display.ContentDisplay.IContentPartDisplayDriver.BuildDisplayAsync(ContentPart contentPart, ContentTypePartDefinition typePartDefinition, BuildDisplayContext context)
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.BuildDisplayAsync(ContentItem contentItem, BuildDisplayContext context)    
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Etch.OrchardCore.Blocks.EditorJS.Parsers.BlocksParser.RenderAsync(BlockParserContext context, String data) in 
   C:\Users\black\Apps\DevOps\Reducted\src\Modules\Etch.OrchardCore.Blocks\EditorJS\Parsers\BlocksParser.cs:line 106
   at Etch.OrchardCore.Blocks.EditorJS.Parsers.BlocksParser.RenderAsync(BlockBodyPart part) in 
   C:\Users\black\Apps\DevOps\Reducted\src\Modules\Etch.OrchardCore.Blocks\EditorJS\Parsers\BlocksParser.cs:line 76
   at Etch.OrchardCore.Blocks.Drivers.BlockBodyPartDisplay.DisplayAsync(BlockBodyPart part, BuildPartDisplayContext context) in 
   C:\Users\black\Apps\DevOps\Reducted\src\Modules\Etch.OrchardCore.Blocks\Drivers\BlockBodyPartDisplay.cs:line 31
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`
   1.OrchardCore.ContentManagement.Display.ContentDisplay.IContentPartDisplayDriver.BuildDisplayAsync(ContentPart contentPart, ContentTypePartDefinition typePartDefinition, BuildDisplayContext context)
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.BuildDisplayAsync(ContentItem contentItem, BuildDisplayContext context)`

**Comment by peterkeating** [comment]
@daveblack101 What was the content within the block editor that caused this issue?

**Comment by daveblack101** [comment]
It happens whenever I open or close an edit page that contains the block editor. Having said that, let me test the latest version and update you if the issue still persists.
